// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk0URWUXFpUpYXAkm5RlERxJ9dc80yijg',
    appId: '1:550104488908:web:b8bf467c5872b426771b69',
    messagingSenderId: '550104488908',
    projectId: 'looksbeyondapp',
    authDomain: 'looksbeyondapp.firebaseapp.com',
    storageBucket: 'looksbeyondapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFa7Ku_8sVeypg_X-M-jEAGcSia4Nleus',
    appId: '1:550104488908:android:1a2ca57a6bf76a5d771b69',
    messagingSenderId: '550104488908',
    projectId: 'looksbeyondapp',
    storageBucket: 'looksbeyondapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXP3og0V9q0d-kGdhq732Ros1RnbMfPAc',
    appId: '1:550104488908:ios:1d618586857fb7ea771b69',
    messagingSenderId: '550104488908',
    projectId: 'looksbeyondapp',
    storageBucket: 'looksbeyondapp.appspot.com',
    iosClientId: '550104488908-rh5r2tk6jimpve8re6s5ppm3etmkrppa.apps.googleusercontent.com',
    iosBundleId: 'com.akshat.looksbeyond',
  );
}
